### ISSUE TITLE
Update tags.yaml for L2T version 20230717

### ISSUE THREAD

**Issue by bit4n6** [blueteam0ps/AllthingsTimesketch#12]
Fields "_parser_chain" and "_event_values_hash" have been removed from OpenSearch output in Log2Timeline version 20230717 (see https://github.com/log2timeline/plaso/issues/4597). Since the very most of the rules in your "tags.yaml" include the "_parser_chain" field, they do not yield results after the Timesketch platform has been upgraded to this L2T version.

**Comment by blueteam0ps** [comment]
@bit4n6 Tx for reporting this. I will be making an update with improvements and fixes in the near future.

**Comment by blueteam0ps** [comment]
@bit4n6  This has been fixed up via https://github.com/blueteam0ps/AllthingsTimesketch/pull/13
