### ISSUE TITLE
Error: EISDIR: illegal operation on a directory

### ISSUE THREAD

**Issue by rmfooty** [blueteam0ps/AllthingsTimesketch#4]
Hi. I am currently using Node-Red Docker, and get the following error. Has anyone seen this before?

"failed to write to file: Error: EISDIR: illegal operation on a directory, open '/data/cases/processor/rich320210922t125635z/C/Windows/System32/wbem/'"

**Comment by blueteam0ps** [comment]
I am already aware of this edge case as I've seen it in one of the data tests I've tested.

**Comment by blueteam0ps** [comment]
This was isolated to be an edge case and I could not get it fixed using Node-RED's unzip node. Therefore, in order for the flow to be consistent, I've changed the flow to use Linux's unzip utility instead (using an exec node). Please grab the latest json and it should work for you. Closing this case now as my tests using the problematic zip file worked with this flow.

**Comment by rmfooty** [comment]
Thank you for your help. The latest json file only contains 12 lines of code :(

**Comment by blueteam0ps** [comment]
Sorry abt that.. Try now
