### ISSUE TITLE
no .env file 

### ISSUE THREAD

**Issue by mcdave2k1** [blueteam0ps/AllthingsTimesketch#6]
hey blueteam0ps,

can you provide a .env file ?

![image](https://user-images.githubusercontent.com/36896028/197314751-1f854e2d-2b03-4c67-986d-fc94503d476e.png)

**Comment by blueteam0ps** [comment]
Looks like the command below which is part of the shell script may hve not worked for u ?
 curl -s -O https://raw.githubusercontent.com/google/timesketch/master/contrib/deploy_timesketch.sh
 It contains the following. I do not manage Timesketch so you will have to troubleshoot at your end. Looks like the above shell script provided by the Timesketch repo is not getting run 100% for u.

# Docker compose and configuration
echo -n "* Fetching configuration files.."
curl -s $GITHUB_BASE_URL/docker/release/docker-compose.yml > timesketch/docker-compose.yml
curl -s $GITHUB_BASE_URL/docker/release/config.env > timesketch/config.env
